language: python

os:
  - linux

python:
  - 3.6

addons:
  apt:
    packages:
    - python-setuptools

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --add channels conda-forge
  - conda create -n myenv python=3.7
  - conda activate myenv
  - pip install tensorflow==2.3
  - pip install torch==1.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
  - pip install torch_scatter==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.6.0.html
  - pip install torch_cluster==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.6.0.html
  - pip install torch_sparse==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.6.0.html
  - pip install torch-spline-conv==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.6.0.html
  - pip install torch_geometric
  - pip install uproot
  - pip install matplotlib networkx numba scipy numpy comet_ml setGPU pandas mplhep tqdm sklearn


script:
  - ./scripts/local_test.sh
