backend: tensorflow

dataset:
  schema: delphes
  target_particles: gen
  num_input_features: 12
  num_output_features: 7
  #(none=0, track=1, cluster=2)
  num_input_classes: 3
  num_output_classes: 6
  num_momentum_outputs: 5
  padded_num_elem_size: 6400
  classification_loss_coef: 1.0
  charge_loss_coef: 0.1
  pt_loss_coef: 1.0
  eta_loss_coef: 0.1
  sin_phi_loss_coef: 1.0
  cos_phi_loss_coef: 1.0
  energy_loss_coef: 1.0
  raw_path: data/pythia8_ttbar/raw/*.pkl.bz2
  processed_path: data/pythia8_ttbar/tfr/*.tfrecords
  num_files_per_chunk: 5
  validation_file_path: data/pythia8_qcd/val/*.pkl.bz2
  energy_loss:
    type: Huber
    delta: 1.0
  pt_loss:
    type: Huber
    delta: 1.0
  sin_phi_loss:
    type: Huber
    delta: 0.1
  cos_phi_loss:
    type: Huber
    delta: 0.1
  eta_loss:
    type: Huber
    delta: 0.1
    
tensorflow:
  eager: no

setup:
  train: yes
  weights: 
  lr: 1e-4
  batch_size: 5
  num_events_train: 4000
  num_events_test: 10000
  num_epochs: 10
  num_val_files: 2
  dtype: float32
  trainable: all
  multi_output: yes
  classification_loss_type: categorical_cross_entropy
  lr_schedule: exponentialdecay  # exponentialdecay, onecycle

sample_weights:
  cls: inverse_sqrt
  charge: signal_only
  pt: signal_only
  eta: signal_only
  sin_phi: signal_only
  cos_phi: signal_only
  energy: signal_only

parameters:
  model: gnn_dense
  input_encoding: default
  activation: elu
  layernorm: no
  hidden_dim: 256
  bin_size: 32
  distance_dim: 16
  dropout: 0.0
  graph_kernel:
    type: NodePairTrainableKernel
    output_dim: 32
    hidden_dim: 32
    num_layers: 2
    activation: elu
  num_graph_layers: 3
  node_message:
    type: NodeMessageLearnable
    output_dim: 256
    hidden_dim: 128
    num_layers: 3
    activation: elu
    aggregation_direction: dst
  num_node_messages: 1
  skip_connection: yes
  regression_use_classification: yes
  debug: no

timing:
  num_ev: 100
  num_iter: 3

exponentialdecay:
  decay_steps: 10000
  decay_rate: 0.99
  staircase: yes
