tensorflow:
  eager: no

setup:
  train: yes
  weights: experiments/delphes-transformer-skipconn-a4f27e29/weights.89-0.170756.hdf5
  lr: 1e-7
  batch_size: 5
  num_events_train: 200000
  num_events_test: 50000
  num_epochs: 100
  dtype: float32
  sample_weights: none

parameters:
  model: transformer
  num_layers: 4
  d_model: 256
  num_heads: 4
  dff: 256
  support: 32
  skip_connection: yes
