tensorflow:
  eager: no

setup:
  train: yes
  weights:
  lr: 5e-5
  batch_size: 5
  num_events_train: 4000
  num_events_test: 1000
  num_epochs: 20
  dtype: float32

parameters:
  model: transformer
  num_layers: 2
  d_model: 256
  num_heads: 4
  dff: 256
  support: 32
