tensorflow:
  eager: no

setup:
  train: yes
  weights:
  lr: 1e-4
  batch_size: 1
  num_events_train: 200000
  num_events_test: 50000
  num_epochs: 40
  dtype: float32

parameters:
  model: transformer
  num_layers: 2
  d_model: 256
  num_heads: 4
  dff: 256
  support: 32
