tensorflow:
  eager: no

setup:
  train: yes
  weights:
  lr: 1e-5
  batch_size: 5
  num_events_train: 200000
  num_events_test: 50000
  num_epochs: 100
  dtype: float32
  sample_weights: none

parameters:
  model: dense
