tensorflow:
  eager: no

setup:
  train: yes
  weights:
  lr: 1e-4
  batch_size: 10
  num_events_train: 4000
  num_events_test: 1000
  num_epochs: 10
  dtype: float32

parameters:
  model: gnn
  bin_size: 128
  num_convs_id: 2
  num_convs_reg: 2
  num_hidden_id_enc: 1
  num_hidden_id_dec: 1
  num_hidden_reg_enc: 1
  num_hidden_reg_dec: 1
  num_neighbors: 16 
  hidden_dim_id: 256
  hidden_dim_reg: 256
  distance_dim: 256
  dropout: 0.1
  dist_mult: 1.0
  activation: elu
