tensorflow:
  eager: no

setup:
  train: yes
  weights:
  lr: 1e-6
  batch_size: 5
  num_events_train: 200000
  num_events_test: 50000
  num_epochs: 100
  dtype: float32
  sample_weights: none

parameters:
  model: transformer
  num_layers: 4
  d_model: 256
  num_heads: 4
  dff: 256
  support: 32
  skip_connection: yes
