name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  deps-torch:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"
          cache: "pip"
      - run: pip install -r requirements.txt

  torch-unittests:
    runs-on: ubuntu-22.04
    needs: [deps-torch]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"
          cache: "pip"
      - run: pip install -r requirements.txt
      - run: PYTHONPATH=. python3 -m unittest tests/test_torch_and_tf.py

  torch-pipeline:
    runs-on: ubuntu-22.04
    needs: [torch-unittests]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"
          cache: "pip"
      - run: pip install -r requirements.txt
      - run: ./scripts/local_test_torch.sh
