name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  delphes-tf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python deps
        run: |
          sudo apt install python3 python3-pip wget
          sudo python3 -m pip install --upgrade pip
          sudo python3 -m pip install --upgrade setuptools
          sudo python3 -m pip install tensorflow==2.3 setGPU sklearn matplotlib mplhep pandas scipy uproot3 uproot3-methods awkward0 keras-tuner networkx
      - name: Run delphes TF model
        run: ./scripts/local_test_delphes_tf.sh

  cms-tf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python deps
        run: |
          sudo apt install python3 python3-pip wget
          sudo python3 -m pip install --upgrade pip
          sudo python3 -m pip install --upgrade setuptools
          sudo python3 -m pip install tensorflow==2.3 setGPU sklearn matplotlib mplhep pandas scipy uproot3 uproot3-methods awkward0 keras-tuner networkx
      - name: Run CMS TF model
        run: ./scripts/local_test_cms_tf.sh