# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install python deps
        run: |
          sudo apt install python3 python3-pip wget
          sudo python3 -m pip install --upgrade pip
          sudo python3 -m pip install --upgrade setuptools
          sudo python3 -m pip install tensorflow==2.3 setGPU sklearn matplotlib mplhep pandas scipy uproot3 uproot3-methods awkward0 keras-tuner

  delphes-tf:
    needs: setup
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Run delphes TF test
        run: ./scripts/local_test_delphes_tf.sh

  cms-tf:
    needs: setup
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Run CMS TF test
        run: ./scripts/local_test_cms_tf.sh
